language: python
cache: pip
python: 
  - "2.7"
before_install:
  - pip install cpp-coveralls
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install PySide pytest-qt pytest-mock
  - make COVERAGE=1
script: pytest -v -s
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
